### ISSUE TITLE
！！编译报错，求助。

### ISSUE THREAD

**Issue by Autocader** [LYU4662/t95zplus-h618-build#1]
![捕获11](https://github.com/user-attachments/assets/5052219a-ec99-4257-8ae2-937b07bf5501)
你好，LYU4662
我编译时出现错误，不知道什么原因，能否指导一下。
我手上有一个T95zPlus板子，想要这个系统镜像，可支付一定费用。
我的邮箱是157330417@qq.com，盼复。

**Comment by LYU4662** [comment]
你网络问题，系统镜像在release里，自己下载就行了啊

**Comment by Autocader** [comment]
> 你网络问题，系统镜像在release里，自己下载就行了啊

感谢你的回复，release的镜像安装后发现没有WIFI, 不知是不是这个镜像里面没有编译驱动进去。我完全不懂，是否可以加WX指导一下 **T19735** ，或有偿提供一份带驱动的镜像呢。
